bufferSize: 2048
language: cn
pages:
- content: 欢迎来到语音增强质量的主观评测。<br>请单击 [下页] 按钮。
  id: welcome
  name: 语音增强质量评测
  type: generic
- content: 分别播放“干净的”reference 和处理后的音频，然后以 reference 音频作为参照，对处理后的音频的质量进行打分（0 到 100之间）。<br><br><strong>注意：</strong>您需要为每个音频样本进行多个指标的打分，包括语音质量、背景噪声质量和整体音频质量。<br><br><strong>在主观评测的过程中，直到测试结束之前，请不要关闭或重新加载此页面，否则进度将会丢失。</strong><br><br>请单击
    [下页] 按钮。
  id: explanation
  name: 测试介绍
  type: generic
- content: 这是和后面评测中您将听到的音频相似的一个语音样本。请根据它调整耳机的音量。<br><br><strong>在评测过程中，请使用耳机，并在相对安静的房间中进行听音。</strong>
  defaultVolume: 1.0
  id: volume_check
  stimulus: ./configs/resources/samples/clean/sample10_cond1.wav
  type: volume
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_1
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 1 评测 (sample10_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample10_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample10_cond1.wav
    cond10: ./cond10/sample10_cond1.wav
    cond2: ./cond2/sample10_cond1.wav
    cond3: ./cond3/sample10_cond1.wav
    cond4: ./cond4/sample10_cond1.wav
    cond5: ./cond5/sample10_cond1.wav
    cond6: ./cond6/sample10_cond1.wav
    cond7: ./cond7/sample10_cond1.wav
    cond8: ./cond8/sample10_cond1.wav
    cond9: ./cond9/sample10_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_2
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 2 评测 (sample1_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample1_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample1_cond1.wav
    cond10: ./cond10/sample1_cond1.wav
    cond2: ./cond2/sample1_cond1.wav
    cond3: ./cond3/sample1_cond1.wav
    cond4: ./cond4/sample1_cond1.wav
    cond5: ./cond5/sample1_cond1.wav
    cond6: ./cond6/sample1_cond1.wav
    cond7: ./cond7/sample1_cond1.wav
    cond8: ./cond8/sample1_cond1.wav
    cond9: ./cond9/sample1_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_3
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 3 评测 (sample2_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample2_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample2_cond1.wav
    cond10: ./cond10/sample2_cond1.wav
    cond2: ./cond2/sample2_cond1.wav
    cond3: ./cond3/sample2_cond1.wav
    cond4: ./cond4/sample2_cond1.wav
    cond5: ./cond5/sample2_cond1.wav
    cond6: ./cond6/sample2_cond1.wav
    cond7: ./cond7/sample2_cond1.wav
    cond8: ./cond8/sample2_cond1.wav
    cond9: ./cond9/sample2_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_4
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 4 评测 (sample3_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample3_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample3_cond1.wav
    cond10: ./cond10/sample3_cond1.wav
    cond2: ./cond2/sample3_cond1.wav
    cond3: ./cond3/sample3_cond1.wav
    cond4: ./cond4/sample3_cond1.wav
    cond5: ./cond5/sample3_cond1.wav
    cond6: ./cond6/sample3_cond1.wav
    cond7: ./cond7/sample3_cond1.wav
    cond8: ./cond8/sample3_cond1.wav
    cond9: ./cond9/sample3_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_5
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 5 评测 (sample4_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample4_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample4_cond1.wav
    cond10: ./cond10/sample4_cond1.wav
    cond2: ./cond2/sample4_cond1.wav
    cond3: ./cond3/sample4_cond1.wav
    cond4: ./cond4/sample4_cond1.wav
    cond5: ./cond5/sample4_cond1.wav
    cond6: ./cond6/sample4_cond1.wav
    cond7: ./cond7/sample4_cond1.wav
    cond8: ./cond8/sample4_cond1.wav
    cond9: ./cond9/sample4_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_6
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 6 评测 (sample5_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample5_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample5_cond1.wav
    cond10: ./cond10/sample5_cond1.wav
    cond2: ./cond2/sample5_cond1.wav
    cond3: ./cond3/sample5_cond1.wav
    cond4: ./cond4/sample5_cond1.wav
    cond5: ./cond5/sample5_cond1.wav
    cond6: ./cond6/sample5_cond1.wav
    cond7: ./cond7/sample5_cond1.wav
    cond8: ./cond8/sample5_cond1.wav
    cond9: ./cond9/sample5_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_7
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 7 评测 (sample6_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample6_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample6_cond1.wav
    cond10: ./cond10/sample6_cond1.wav
    cond2: ./cond2/sample6_cond1.wav
    cond3: ./cond3/sample6_cond1.wav
    cond4: ./cond4/sample6_cond1.wav
    cond5: ./cond5/sample6_cond1.wav
    cond6: ./cond6/sample6_cond1.wav
    cond7: ./cond7/sample6_cond1.wav
    cond8: ./cond8/sample6_cond1.wav
    cond9: ./cond9/sample6_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_8
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 8 评测 (sample7_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample7_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample7_cond1.wav
    cond10: ./cond10/sample7_cond1.wav
    cond2: ./cond2/sample7_cond1.wav
    cond3: ./cond3/sample7_cond1.wav
    cond4: ./cond4/sample7_cond1.wav
    cond5: ./cond5/sample7_cond1.wav
    cond6: ./cond6/sample7_cond1.wav
    cond7: ./cond7/sample7_cond1.wav
    cond8: ./cond8/sample7_cond1.wav
    cond9: ./cond9/sample7_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_9
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 9 评测 (sample8_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample8_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample8_cond1.wav
    cond10: ./cond10/sample8_cond1.wav
    cond2: ./cond2/sample8_cond1.wav
    cond3: ./cond3/sample8_cond1.wav
    cond4: ./cond4/sample8_cond1.wav
    cond5: ./cond5/sample8_cond1.wav
    cond6: ./cond6/sample8_cond1.wav
    cond7: ./cond7/sample8_cond1.wav
    cond8: ./cond8/sample8_cond1.wav
    cond9: ./cond9/sample8_cond1.wav
  type: multi_metric_mushra
- content:
  - 请对以下指标进行评分：<br>
  - '1. <strong>整体音频质量</strong>: 同时考虑语音和背景噪声的整体质量'
  - '2. <strong>语音质量</strong>: 仅考虑语音信号的质量（不考虑背景噪声）'
  - '3. <strong>背景噪声质量</strong>: 仅考虑背景噪声的质量（不考虑语音信号）'
  - <br>评分标准：<br>
  - '- <strong>整体音频质量</strong>: 0=差（强干扰噪声，高度失真）; 100=优（几乎无噪声，无失真）'
  - '- <strong>语音质量</strong>: 0=高度失真; 100=无失真'
  - '- <strong>背景噪声质量</strong>: 0=几乎无噪声; 100=强干扰噪声'
  - '<br><strong>注意</strong>: 请根据每段音频中噪声的<strong>相对于语音的音量</strong>来评估背景噪声质量'
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: sample_10
  metrics:
  - 整体音频质量
  - 语音质量
  - 背景噪声质量
  mustPlayAll: true
  mustViewAllTabs: true
  name: 样本 10 评测 (sample9_cond1)
  randomize: true
  reference: ./configs/resources/samples/clean/sample9_cond1.wav
  response:
  - - 很好
    - 好
    - 较好
    - 较差
    - 差
  - - 无失真
    - 轻微失真
    - 较失真
    - 相当失真
    - 极度失真
  - - 强干扰噪声
    - 有一定干扰性
    - 有噪声但无干扰性
    - 轻微噪声
    - 几乎无噪声
  showConditionNames: true
  stimuli:
    cond1: ./cond1/sample9_cond1.wav
    cond10: ./cond10/sample9_cond1.wav
    cond2: ./cond2/sample9_cond1.wav
    cond3: ./cond3/sample9_cond1.wav
    cond4: ./cond4/sample9_cond1.wav
    cond5: ./cond5/sample9_cond1.wav
    cond6: ./cond6/sample9_cond1.wav
    cond7: ./cond7/sample9_cond1.wav
    cond8: ./cond8/sample9_cond1.wav
    cond9: ./cond9/sample9_cond1.wav
  type: multi_metric_mushra
- content: 评测结束，请输入您的<strong>名字</strong>，并单击 [提交结果] 按钮。
  id: finish
  name: 评测结束
  popupContent: 您的评测结果已被记录。感谢您的配合！
  questionnaire:
  - label: 名字
    name: name
    optional: false
    type: text
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
showWaveform: true
stopOnErrors: true
testId: subjective_evaluation
testname: Subjective evaluation of Speech Enhancement
